### ISSUE TITLE
Problem with `config` option on Windows.

### ISSUE THREAD

**Issue by vkbansal** [jackfranklin/gulp-load-plugins#76] opened 2015-05-01 17:16 UTC
Plugins does not work on Windows with
```js
{
    config: "package.json"
}
```

Instead must use the following
```js
{
    config: path.join(__dirname, "package.json")
}
```

**Comment by callumacrae** [comment] 2015-05-05 14:23
Why would you want to set `config` to package.json? That's the default!

Does it work with other paths like `../package.json` and `foo/package.json`? Just trying to work out where the problem is—I think it's with the `path.dirname()` call [here](https://github.com/jackfranklin/gulp-load-plugins/blob/master/index.js#L38).

**Comment by fergaldoyle** [comment] 2015-06-09 15:11
`../package.json`  does not work. I'd like to use a `package.json` in the parent directory but it's not working.

**Comment by jackfranklin** [comment] 2015-11-05 10:26
Did we ever get anywhere with this? I'm wondering if `config: path.join(__dirname, './package.json')` works more reliably across OS's then maybe we should make that the default?

**Comment by jackfranklin** [comment] 2016-01-05 10:29
Closing - if anyone else finds this issue please let me know.

**Closed by jackfranklin** 2016-01-05 10:29 UTC
